alter table goals
    add column if not exists baseline_amount numeric(12, 2);

create table if not exists goal_asset_links (
    id bigint generated by default as identity primary key,
    goal_id bigint not null references goals(id) on delete cascade,
    asset_name text not null
);

create index if not exists idx_goal_asset_links_goal_id on goal_asset_links(goal_id);
