create table if not exists goal_shares (
    id bigint generated by default as identity primary key,
    goal_id bigint not null references goals(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade
);

create unique index if not exists idx_goal_shares_unique
    on goal_shares(goal_id, user_id);

create table if not exists asset_shares (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null references users(id) on delete cascade,
    shared_user_id bigint not null references users(id) on delete cascade,
    asset_name text not null
);

create unique index if not exists idx_asset_shares_unique
    on asset_shares(owner_user_id, shared_user_id, asset_name);

create table if not exists transaction_splits (
    id bigint generated by default as identity primary key,
    transaction_id bigint not null references transactions(id) on delete cascade,
    participant_user_id bigint not null references users(id) on delete cascade,
    share_ratio numeric(6, 4) not null default 0.5,
    settlement_amount numeric(12, 2),
    note text
);

create unique index if not exists idx_transaction_splits_unique
    on transaction_splits(transaction_id, participant_user_id);
